
universe = vanilla

# getenv = true

executable = condor_exec.sh

arguments = $(ExecutableFile) $(InputFile) $(OutputFile) $(ParamsFile) $(ClusterId) $(ProcId)

# input = input/indata-$(ProcId)

transfer_input_files = $(InputFile)

stdout = stdout/stdout-ClusterId$(ClusterId)-ProcId$(ProcId).ansi
stderr = stderr/stderr-ClusterId$(ClusterId)-ProcId$(ProcId).err
log = condorlog/condorlog-ClusterId$(ClusterId).log

request_cpus = 1
request_memory = 8G
request_disk = 8G

should_transfer_files = yes
when_to_transfer_output = on_exit

queue ExecutableFile, InputFile, OutputFile, ParamsFile from CondorSubmitFileList.txt
