
universe = vanilla

# getenv = true

executable = condor_exec.sh
arguments = $(ClusterId) $(ProcId)

# input = input/indata-$(ProcId)

stdout = stdout/stdout-ClusterId$(ClusterId)-ProcId$(ProcId).out
stderr = stderr/stderr-ClusterId$(ClusterId)-ProcId$(ProcId).err
log = condorlog/condorlog-ClusterId$(ClusterId).log

# request_cpus = 1
# request_memory = 8000M
# request_disk = 16000K

should_transfer_files = yes
when_to_transfer_output = on_exit

queue 1
