
rekbmtf_params: # params are specified separately for each "data_type"

    data:
        submission_type: "cern-crab" # job submission evironment: "cern-crab", "aachen-condor"
        submission_splitting: "automatic" # job splitting specification (only for "cern-crab")
        
        output_type: "cern-grid" # output type of data from the jobs: "cern-grid", "aachen-netdir"
        output_site: "T2_DE_RWTH" # output site name (only for "cern-grid")
        output_basepath: "/store/user/nesper/test_analysis_hscp_l1/" # output base path, where the files are stored

        crab_config_template_filepath: "%%%ANALYSIS_CONTROLLER_REPO_PATH%%%/templates/rekbmtf_data_crab_cfg.py" # crab .py template file for the job to be submitted (some wildcards in this template may be filled automatically with the params given in the config)

        cmssw_src_path: "%%%ANALYSIS_CONTROLLER_REPO_PATH%%%/../1_reKBMTF/CMSSW_14_0_12/src/" # cmssw src directory (CMSSW_X_X_XX/src directory), where the cmsenv command is executed
        cmssw_config_template_filepath: "%%%ANALYSIS_CONTROLLER_REPO_PATH%%%/templates/rekbmtf_data_cmssw_cfg.py" # cmssw _cfg.py template file for the job to be submitted (some wildcards in this template may be filled automatically with the params given in the config)
