SkimmingInput:

    union_label: rekbmtf_data_2024H_test

    rekbmtf_collections:
    
        -   user_label: rekbmtf_data_Scouting_2024H_single-file_2026-07-09_11-16-27
            rekbmtf_output_config: ++++ANALYSIS_CONTROLLER_REPO_PATH++++/collections/rekbmtf_data_Scouting_2024H_2026-07-09_11-16-27/single-file_ConfigRekbmtfOutput.yaml

