RekbmtfInput:
    ### FOR DATA

    # data_type: "data"
    # data_label: "Scouting_2024H"
    # input_das_name: "/L1Scouting/Run2024H-v1/L1SCOUT"
    # input_lumi_mask: "https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions24/Cert_Collisions2024_378981_386951_Golden.json"
    # input_run_range: ""

    # data_type: "data"
    # data_label: "Scouting_2024I"
    # input_das_name: "/L1Scouting/Run2024I-v1/L1SCOUT"
    # input_lumi_mask: "https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions24/Cert_Collisions2024_378981_386951_Golden.json"
    # input_run_range: ""

    # data_type: "data"
    # input_das_name: "/L1Scouting/Run2024G-v1/L1SCOUT"
    # input_lumi_mask: "https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions24/Cert_Collisions2024_378981_386951_Golden.json"
    # data_label: "Scouting_2024G_383804-384149"
    # input_run_range: "383804-384149"
    # data_label: "Scouting_2024G_384150-384465"
    # input_run_range: "384150-384465"
    # data_label: "Scouting_2024G_384466-384876"
    # input_run_range: "384466-384876"
    # data_label: "Scouting_2024G_384877-385178"
    # input_run_range: "384877-385178"
    # data_label: "Scouting_2024G_385179-385511"
    # input_run_range: "385179-385511"
    # data_label: "Scouting_2024G_385512-385813"
    # input_run_range: "385512-385813"