FinalSelectionParams:

    submission_type: aachen-condor
    submission_splitting: rootfiles
    
    output_type: aachen-net
    output_site: ""
    output_basepath: /net/data_cms3a-1/esper/test_analysis_hscp_l1/analysis_controller_output/

    executable: /home/home1/institut_3a/esper/promotion/test_analysis_hscp_l1/analysis_controller_repository/scripts_analysis/finalselection/finalselection_slowdata.sh

    request_cpus: 1
    request_memory: 8000M
    request_disk: 16000K

    analysis_params:

