FinalSelectionInput:

    collections:
    
        -   user_label: "rekbmtf_data_Scouting_2024H_2026-07-09_11-16-27_single-file"
            rekbmtf_output_config: /home/home1/institut_3a/esper/promotion/test_analysis_hscp_l1/analysis_controller_repository/collections/rekbmtf_data_Scouting_2024H_2026-07-09_11-16-27/single-file_ConfigRekbmtfOutput.yaml

        # -   user_label: ""
        #     rekbmtf_output_config: /home/home1/institut_3a/esper/promotion/test_analysis_hscp_l1/analysis_controller_repository/collections/rekbmtf_data_Scouting_2024H_2026-07-09_11-16-27/ConfigRekbmtfOutput.yaml

        # -   user_label: ""
        #     rekbmtf_output_config: /home/home1/institut_3a/esper/promotion/test_analysis_hscp_l1/analysis_controller_repository/collections/rekbmtf_data_Scouting_2024I_2026-07-15_17-37-53/ConfigRekbmtfOutput.yaml